package com.babailiren.ec.enumeration;

public enum CacheName {
	BRAND_BY_CATEGORY_ID,
	BRAND_BY_PK,
	BRAND_ALL_LIST,
	CATEGORY_BY_PK,
	CATEGORY_BY_PATH,
	CATEGORY_TREE,
	CATEGORY_BY_ID,
	ATTR_BY_CATEGORY_ID,
	SITE_BY_DOMAIN,
	SITE_BY_PK,
	PRICE_RANGE_BY_SITEID,
	ITEM_ID_URL_MAP;
	
	
}
